server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: users-service
        uri: lb://users-service
        predicates:
        - Path=/users/**
        filters:
        - RewritePath=/users/(?<path>.*), /$\{path}

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URL}
